maikusobu/QuanLyDangKyMonHocVaThuPhiSV-ApiService

.github/workflows/buildAndTest.yml
.github/workflows/deploy.yml
src/config/configuration.ts

feat: update deploy pipeline

---

Dockerfile

feat: update structure code

---

src/repository/auth/auth.repostiory.ts
src/repository/user/user.repository.ts

feat: update jwt

---

src/repository/auth/auth.repostiory.ts

- Internal server error when sign in with an admin account
- Closes #

fix: fix generateToken in auth.repository.ts

---

src/main.ts

-
- Related Issue #29 
- Closes #29

refactor: changing structure project

---

src/main.ts
src/module/course/dto/create-course.dto.ts
src/repository/course/course.repository.ts

- Form validations in the front end depend on backend dto messages
- Closes #

added custom messages in create-course.dto.ts, small fix in course.repository.ts

---

src/db/schema/student.ts
src/db/seed.ts
src/main.ts
src/module/student/dto/create-student.dto.ts
src/module/student/student.controller.ts
src/module/student/student.service.ts
src/repository/student/student.repository.ts

- [] Refactor
-
- Related Issue #35 
- Closes #35

feat: update query student, update schema student

---

src/module/major/major.controller.ts
src/module/major/major.service.ts
src/repository/major/major.repository.ts
src/util/constants.ts

-
- Related Issue #5 
- Closes #

feat: added find program by major id endpoint

---

src/app.module.ts
src/module/index.ts
src/module/program-item/program-item.controller.ts
src/module/program-item/program-item.module.ts
src/module/program-item/program-item.service.ts
src/repository/program-item/program-item.repository.ts
src/util/constants.ts

-
- Related Issue #5 
- Closes #

feat: added delete program item feature

---

src/db/schema/programItem.ts
src/module/course/dto/create-course.dto.ts
src/module/program-item/dto/create-program-item.dto.ts
src/module/program-item/dto/update-program-item.dto.ts
src/module/program-item/program-item.controller.ts
src/module/program-item/program-item.service.ts
src/repository/program-item/program-item.repository.ts
src/util/constants.ts

-
- Related Issue #5 
- Closes #

feat: added update and create program item feature

---

src/db/seed/permission.ts
src/module/course-registration/course-registration.controller.ts
src/module/major/major.controller.ts
src/module/priority/priority.controller.ts
src/module/province/province.controller.ts
src/module/student/student.controller.ts
src/util/constants.ts

chore: setup permission seed

---

src/module/course/dto/create-course.dto.ts
src/module/program-item/dto/create-program-item.dto.ts

chore: added some validation messages in create program item and course

---

src/db/permission-seed.ts
src/db/seed/permission.ts

feat: create seed for permission

---

drizzle.config.ts
package-lock.json
package.json

chore: update drizzle kit, update drizzle.config.ts

---

docker-compose.dev.yml
drizzle.config.ts
package-lock.json
package.json
src/app.module.ts
src/config/configuration.ts
src/module/course-registration/course-registration.controller.ts
src/module/course-registration/course-registration.service.ts
src/module/setupModule/repository/repository.module.ts
src/repository/course-registration/course-registration.repository.ts
src/repository/course-registration/helper/resolveTerm.ts
src/repository/priority/priority.repository.ts
src/repository/student/student.repository.ts
src/util/constants.ts

feat: add server service

---

src/module/course-open/course-open.controller.ts
src/module/course-open/course-open.service.ts
src/repository/course-open/course-open-term.repository.ts

fix: small changes in course-open module

---

src/module/payment/dto/find-payment.dto.ts
src/module/payment/payment.controller.ts
src/module/payment/payment.service.ts
src/repository/payment/payment.repository.ts

fix: small changes in payment module, fix some query bugs

---

src/module/course-open/course-open.controller.ts
src/module/course-open/course-open.service.ts

fix: small conflict in courseopen

---

src/module/course/course.module.ts

fix: import missing modules in course.module.ts

---

src/module/course-open/course-open.controller.ts
src/util/constants.ts

temporary fix in course open module

---

src/main.ts

fix: add at guard

---

src/main.ts

fix: false origin
